packages:
  # Приложения
  - 'apps/*'
  
  # Пакеты
  - 'packages/*'
  
  # Исключения
  - '!**/node_modules/**'
  - '!**/dist/**'
  - '!**/build/**'
  - '!**/.next/**'
  - '!**/coverage/**'
  - '!**/.turbo/**'
